GET http://127.0.0.1:5000/api/admin HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGYzYTZlMDliYzk2Yzg3MTA4MjQyNjIiLCJpYXQiOjE1NzY4MTMxMDAsImV4cCI6MTU3Njg0OTEwMH0.pfNNwxlvjTXRiKJExBByLHEIAvYfWzAU3bzIG5mjuwU
